name: bob
version: 1.4.0.7

dependencies:
  - base

library:
  exposed-modules:
    - Bob

  source-dirs: src
  dependencies:
    - regex-posix

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
