name: pangram
version: 1.4.1.7

dependencies:
  - base

library:
  exposed-modules: Pangram
  source-dirs: src
  dependencies:
  - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
